services:
  db:
    image: postgres:latest
    container_name: arena-postgres
    restart: always
    ports:
      - '6001:5432'
    environment:
      POSTGRES_USER: arena
      POSTGRES_PASSWORD: arena123
      POSTGRES_DB: arena_1
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
