services:
  db:
    image: postgres:latest
    container_name: arena-postgres
    restart: unless-stopped
    ports:
      - '6001:5432'
    environment:
      POSTGRES_USER: arena
      POSTGRES_PASSWORD: arena123
      POSTGRES_DB: arena_1
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: arena-redis
    restart: unless-stopped
    ports:
      - '6002:6379'
    volumes:
      - redis_data:/data
  
volumes:
  postgres_data:
  redis_data:
