services:
  db:
    image: postgres:latest
    container_name: arena-postgres
    restart: unless-stopped
    ports:
      - '6001:5432'
    environment:
      POSTGRES_USER: arena
      POSTGRES_PASSWORD: arena123
      POSTGRES_DB: arena_1
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: arena-redis
    restart: unless-stopped
    ports:
      - '6002:6379'
    volumes:
      - redis_data:/data

  livekit:
    image: livekit/livekit-server:latest
    container_name: arena-livekit
    restart: unless-stopped
    ports:
      - "7880:7880"
      - "50000-50049:50000-50049/udp"
    volumes:
      - ./livekit.yaml:/etc/livekit/livekit.yaml
    command: ["--config", "/etc/livekit/livekit.yaml"]

  corturn:
    image: coturn/coturn:latest
    container_name: arena-coturn
    restart: unless-stopped
    ports:
      - "3478:3478/udp"
      - "3478:3478/tcp"
      - "5349:5349/tcp"
      - "62000-62049:62000-62049/udp"           # 미디어 포트 범위
    volumes:
      - ./turnserver.conf:/etc/turnserver.conf:ro
  
volumes:
  postgres_data:
  redis_data:
